"use client";

import { useEffect, useRef, useState } from "react";
import type { ChangeEvent, ReactNode } from "react";
import "./app.css";

type Rating = 1 | 2 | 3 | 4 | 5;
type Meal = { id:string; name:string; calories:number; protein:number; fat:number; carbs:number };
type Song = { id:string; title:string; url:string; mastery:number; notes:string; lastPracticed?:string };
type Exercise = { id:string; title:string; completed:boolean; count?:number; bpm?:number; speed?:number; rating?:number; notes?:string; checks?:Record<string,boolean> };
type Day = {
  date:string; started:boolean; saved:boolean; initialEnergy:number|null; finalEnergy:number|null; attention:number|null; satisfaction:number|null;
  priority:string; dailyNote:string; meals:Meal[]; nutritionClosed:boolean; squatCompleted:boolean; squatReps:number; squatTechnique:number|null; squatNote:string; videoName:string;
  reading:{target:number; seconds:number; attention:number|null; comprehension:number|null; summary:string; completed:boolean};
  exercises:Exercise[]; songs:Record<string,{checks:Record<string,boolean>; difficulty:number|null; notes:string}>;
  bestResult:string; correction:string; nextPriority:string;
};
type Settings = { calories:number; protein:number; fat:number; carbs:number; readingMinutes:number; theme:"light"|"dark"; visible:Record<string,boolean> };
type AppData = { version:1; settings:Settings; days:Record<string,Day>; repertoire:Song[]; vocabulary:{id:string;date:string;word:string;meaning:string;example:string}[]; lastFocus:number };

const priorities=["Lectura","Técnica de guitarra","Ritmo","Diapasón","Repertorio","Sentadilla","Nutrición"];
const exerciseSeeds:Exercise[]=[
  {id:"strum1",title:"Rasgueos nivel 1 · ejercicios 1–4",completed:false,count:0,checks:{"Sin drums":false,"Contar en voz alta":false,"Usar el pie":false}},
  {id:"cg",title:"20 repeticiones adicionales de C–G",completed:false,count:0},
  {id:"drums",title:"Rasgueos con drums · nivel 1 y 2",completed:false,bpm:70,rating:0,checks:Object.fromEntries(["N1 · 5","N1 · 6","N2 · 1","N2 · 2","N2 · 3","N2 · 4","N2 · 5","N2 · 6"].map(x=>[x,false]))},
  {id:"patterns",title:"Patrones de Good Riddance",completed:false,count:0,bpm:60,speed:.6,rating:0,checks:{"Cambio de acordes":false}},
  {id:"pentatonic",title:"Pentatónica con plumilla · CAGED",completed:false,count:0,rating:0,checks:Object.fromEntries(["C","A","G","E","D"].map(x=>[x,false]))},
  {id:"chords",title:"Posiciones de acordes · E A D C G",completed:false,checks:Object.fromEntries(["E aprendida","A aprendida","D aprendida","C aprendida","G aprendida","Nombrarlas","Moverlas por el diapasón"].map(x=>[x,false]))},
  {id:"barre",title:"Cejilla de E · sostenidos y bemoles",completed:false,count:0},
  {id:"good",title:"Good Riddance completa · velocidad 0.55",completed:false,count:0,speed:.55,rating:0,checks:Object.fromEntries(["Acordes correctos","Todos los números","Todos los “y”","Picking correcto","Orden correcto","Dirección arriba/abajo","Velocidad 0.55","De principio a fin"].map(x=>[x,false]))},
];
const defaults:Settings={calories:2000,protein:180,fat:40,carbs:230,readingMinutes:5,theme:"light",visible:{nutrition:true,reading:true,guitar:true,caged:true,repertoire:true,review:true}};
const key="bruno-guitarra-v1";
const today=()=>new Date().toLocaleDateString("en-CA");
const makeDay=(settings=defaults,date=today()):Day=>({date,started:false,saved:false,initialEnergy:null,finalEnergy:null,attention:null,satisfaction:null,priority:"",dailyNote:"",meals:[],nutritionClosed:false,squatCompleted:false,squatReps:0,squatTechnique:null,squatNote:"",videoName:"",reading:{target:settings.readingMinutes,seconds:settings.readingMinutes*60,attention:null,comprehension:null,summary:"",completed:false},exercises:structuredClone(exerciseSeeds),songs:{},bestResult:"",correction:"",nextPriority:""});
const initialData=():AppData=>({version:1,settings:defaults,days:{},repertoire:[{id:"wonderwall",title:"Wonderwall",url:"https://www.youtube.com/watch?v=LRXRm0eMZZY",mastery:0,notes:""}],vocabulary:[],lastFocus:0});
const taskCount=(d:Day)=>8+d.exercises.length;
const exerciseDone=(exercise:Exercise)=>exercise.completed||(exercise.id==="barre"&&(exercise.count||0)>0);
const completedCount=(d:Day)=>[d.started,d.nutritionClosed,d.squatCompleted,d.reading.completed,...d.exercises.map(exerciseDone),Object.keys(d.songs).length>0,d.saved].filter(Boolean).length;
const pct=(d:Day)=>Math.round(completedCount(d)/taskCount(d)*100);
const notes=["Do","Do♯ / Re♭","Re","Re♯ / Mi♭","Mi","Fa","Fa♯ / Sol♭","Sol","Sol♯ / La♭","La","La♯ / Si♭","Si"];
const openStrings=[4,11,7,2,9,4];

function RatingScale({value,onChange,label}:{value:number|null|undefined;onChange:(n:Rating)=>void;label:string}){return <div className="rating" aria-label={label}>{[1,2,3,4,5].map(n=><button type="button" key={n} aria-label={`${label}: ${n} de 5`} className={value===n?"active":""} onClick={()=>onChange(n as Rating)}>{n}</button>)}</div>}
function Progress({value,label}:{value:number;label?:string}){return <div><div className="progress-label"><span>{label}</span><strong>{value}%</strong></div><div className="bar" role="progressbar" aria-valuenow={value} aria-valuemin={0} aria-valuemax={100}><i style={{width:`${Math.min(value,100)}%`}}/></div></div>}
function Card({title,eyebrow,done,children,onDone}:{title:string;eyebrow?:string;done?:boolean;children:ReactNode;onDone?:()=>void}){return <section className={`card ${done?"done":""}`}><div className="card-head"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2></div>{onDone&&<button className="check" onClick={onDone} aria-label={done?`Reabrir ${title}`:`Completar ${title}`}>{done?"✓":"○"}</button>}</div>{children}</section>}
function Field({label,type,onChange,onBlur,onFocus,value,...props}:{label:string}&React.InputHTMLAttributes<HTMLInputElement>){
  const [numberDraft,setNumberDraft]=useState<string|null>(null);
  const isNumber=type==="number";
  return <label className="field"><span>{label}</span><input {...props} type={type} value={isNumber?(numberDraft??value):value} inputMode={isNumber?"decimal":props.inputMode} onFocus={event=>{if(isNumber)event.currentTarget.select();onFocus?.(event)}} onChange={event=>{if(isNumber)setNumberDraft(event.target.value);onChange?.(event)}} onBlur={event=>{if(isNumber)setNumberDraft(null);onBlur?.(event)}}/></label>
}

export default function Home(){
  const [data,setData]=useState<AppData>(initialData); const [ready,setReady]=useState(false); const [tab,setTab]=useState("today"); const [focus,setFocus]=useState(false); const [timer,setTimer]=useState(false); const [toast,setToast]=useState("");
  const [quiz,setQuiz]=useState({string:0,fret:0,answer:"",shown:false,hits:0,misses:0,mode:"mixto"}); const tick=useRef<ReturnType<typeof setInterval>|null>(null);
  useEffect(()=>{queueMicrotask(()=>{try{const raw=localStorage.getItem(key);if(raw){const parsed=JSON.parse(raw);if(parsed.version===1)setData(parsed)}}catch{}setReady(true)});navigator.serviceWorker?.register("./sw.js").catch(()=>{})},[]);
  useEffect(()=>{if(!ready)return;localStorage.setItem(key,JSON.stringify(data));document.documentElement.dataset.theme=data.settings.theme},[data,ready]);
  const day=data.days[today()]??makeDay(data.settings); const updateDay=(fn:(d:Day)=>Day)=>setData(x=>({...x,days:{...x.days,[today()]:fn(x.days[today()]??makeDay(x.settings))}}));
  useEffect(()=>{if(timer){tick.current=setInterval(()=>updateDay(d=>{const seconds=Math.max(0,d.reading.seconds-1);if(seconds===0)queueMicrotask(()=>{setTimer(false);setToast("Tiempo de lectura terminado")});return {...d,reading:{...d.reading,seconds}}}),1000)}return()=>{if(tick.current)clearInterval(tick.current)}},[timer]);
  const completion=pct(day); const totals=day.meals.reduce((a,m)=>({calories:a.calories+m.calories,protein:a.protein+m.protein,fat:a.fat+m.fat,carbs:a.carbs+m.carbs}),{calories:0,protein:0,fat:0,carbs:0});
  const updateExercise=(id:string,patch:Partial<Exercise>)=>updateDay(d=>({...d,exercises:d.exercises.map(e=>e.id===id?{...e,...patch}:e)}));
  const start=()=>{if(!day.initialEnergy||!day.priority){setToast("Elige energía y prioridad para comenzar");return}updateDay(d=>({...d,started:true}));setToast("Tu plan está listo")};
  const savedDays=Object.values(data.days).filter(d=>d.saved).sort((a,b)=>b.date.localeCompare(a.date));
  const focusItems=[{title:"Lectura con atención",done:day.reading.completed,action:()=>updateDay(d=>({...d,reading:{...d.reading,completed:true}}))},...day.exercises.map(e=>({title:e.title,done:exerciseDone(e),action:()=>updateExercise(e.id,{completed:true})}))]; const fi=Math.min(data.lastFocus,focusItems.length-1);
  const setSetting=(patch:Partial<Settings>)=>setData(x=>({...x,settings:{...x.settings,...patch}}));
  const exportJson=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download=`bruno-guitarra-${today()}.json`;a.click()};
  const importJson=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const v=JSON.parse(String(r.result));if(v.version!==1||!v.settings||!v.days)throw Error();setData(v);setToast("Respaldo importado")}catch{setToast("Ese archivo no es un respaldo válido")}};r.readAsText(f)};
  const weeklyText=()=>`Semana de Bruno: ${savedDays.slice(0,7).length} días guardados · ${savedDays.slice(0,7).reduce((a,d)=>a+pct(d),0)/Math.max(1,savedDays.slice(0,7).length)|0}% promedio · ${savedDays.slice(0,7).reduce((a,d)=>a+Math.round((d.reading.target*60-d.reading.seconds)/60),0)} min de lectura.`;
  const nextQuiz=()=>setQuiz(q=>({...q,string:Math.floor(Math.random()*6),fret:Math.floor(Math.random()*13),answer:"",shown:false})); const correct=notes[(openStrings[quiz.string]+quiz.fret)%12];
  const answerQuiz=()=>{const ok=correct.toLowerCase().split(" /").some(n=>quiz.answer.trim().toLowerCase()===n.toLowerCase());setQuiz(q=>({...q,shown:true,hits:q.hits+(ok?1:0),misses:q.misses+(ok?0:1)}))};
  if(!ready)return <main className="loading">Afinando la app…</main>;
  return <div className="app">
    <header className="top"><div><span className="brand-mark">B</span><span className="brand">Bruno · práctica diaria</span></div><button className="icon-btn" onClick={()=>setSetting({theme:data.settings.theme==="light"?"dark":"light"})} aria-label="Cambiar tema">{data.settings.theme==="light"?"☾":"☀"}</button></header>
    {toast&&<button className="toast" onClick={()=>setToast("")}>{toast}</button>}
    <main>
      {tab==="today"&&!focus&&<>
        <section className="hero"><div><p className="date">{new Intl.DateTimeFormat("es-MX",{weekday:"long",day:"numeric",month:"long"}).format(new Date())}</p><h1>{day.started?"Sigue con calma, Bruno.":"Hoy toca avanzar."}</h1><p>{day.started?`${completedCount(day)} tareas terminadas. Una cosa a la vez.`:"Decide qué requiere más atención antes de empezar."}</p></div><div className="ring" style={{"--p":`${completion*3.6}deg`} as React.CSSProperties}><strong>{completion}%</strong><span>del día</span></div><Progress value={completion}/><button className="primary focus-button" onClick={()=>setFocus(true)}>◉ Entrar en modo enfoque</button></section>
        {!day.started&&<Card title="Preparación del día" eyebrow="PASO 1"><p>¿Con cuánta energía empiezas?</p><RatingScale value={day.initialEnergy} label="Energía inicial" onChange={n=>updateDay(d=>({...d,initialEnergy:n}))}/><label className="field"><span>Prioridad única</span><select value={day.priority} onChange={e=>updateDay(d=>({...d,priority:e.target.value}))}><option value="">Elige una prioridad</option>{priorities.map(p=><option key={p}>{p}</option>)}</select></label><label className="field"><span>¿Qué necesitas cuidar hoy?</span><textarea placeholder="Ej. tocar lento y limpio" value={day.dailyNote} onChange={e=>updateDay(d=>({...d,dailyNote:e.target.value}))}/></label><button className="primary" onClick={start}>Comenzar el día →</button></Card>}
        {day.started&&<Routine day={day} totals={totals} settings={data.settings} updateDay={updateDay} updateExercise={updateExercise} timer={timer} setTimer={setTimer} setData={setData}/>} 
      </>}
      {(focus||tab==="focus")&&<section className="focus-view"><button className="text-btn" onClick={()=>{setFocus(false);setTab("today")}}>← Salir del enfoque</button><p className="eyebrow">TAREA {fi+1} DE {focusItems.length}</p><h1>{focusItems[fi].title}</h1><p>Haz solamente esta tarea. Respira, cuenta en voz alta y prioriza limpieza.</p><div className="focus-orb">{focusItems[fi].done?"✓":"♪"}</div><button className="primary" onClick={focusItems[fi].action}>{focusItems[fi].done?"Completada":"Completar"}</button><button className="secondary" onClick={()=>setData(x=>({...x,lastFocus:(fi+1)%focusItems.length}))}>Siguiente →</button></section>}
      {tab==="fretboard"&&<Card title="Notas del diapasón" eyebrow="PRÁCTICA"><div className="segmented"><button className={quiz.mode==="mixto"?"active":""} onClick={()=>setQuiz(q=>({...q,mode:"mixto"}))}>Mixto</button><button className={quiz.mode==="examen"?"active":""} onClick={()=>setQuiz(q=>({...q,mode:"examen"}))}>Examen</button></div><div className="quiz"><span>Cuerda {6-quiz.string}</span><strong>Traste {quiz.fret}</strong><p>¿Qué nota es?</p></div><Field label="Tu respuesta" value={quiz.answer} onChange={e=>setQuiz(q=>({...q,answer:e.target.value}))} placeholder="Ej. Fa♯"/><button className="primary" onClick={answerQuiz}>Comprobar</button>{quiz.shown&&<div className="answer">Respuesta: <strong>{correct}</strong></div>}<button className="secondary" onClick={nextQuiz}>Otra nota</button><div className="stats"><div><strong>{quiz.hits}</strong><span>Aciertos</span></div><div><strong>{quiz.misses}</strong><span>Errores</span></div><div><strong>{Math.round(quiz.hits/Math.max(1,quiz.hits+quiz.misses)*100)}%</strong><span>Precisión</span></div></div></Card>}
      {tab==="history"&&<><section className="page-title"><span className="eyebrow">HISTORIAL</span><h1>Tu constancia</h1><p>Avance sin culpas. Cada sesión cuenta.</p></section><div className="stats"><div><strong>{savedDays.length}</strong><span>Días guardados</span></div><div><strong>{savedDays[0]?pct(savedDays[0]):0}%</strong><span>Último día</span></div><div><strong>{savedDays.reduce((a,d)=>a+Math.round((d.reading.target*60-d.reading.seconds)/60),0)}</strong><span>Min. lectura</span></div></div><Card title="Resumen semanal"><p>{weeklyText()}</p><button className="secondary" onClick={()=>navigator.clipboard.writeText(weeklyText()).then(()=>setToast("Resumen copiado"))}>Copiar resumen</button></Card><div className="history-list">{savedDays.length?savedDays.map(d=><article className="history-row" key={d.date}><div className="calendar-day"><strong>{new Date(d.date+"T12:00").getDate()}</strong><span>{new Intl.DateTimeFormat("es",{month:"short"}).format(new Date(d.date+"T12:00"))}</span></div><div><strong>{d.priority||"Práctica diaria"}</strong><span>{completedCount(d)} tareas · {Math.round((d.reading.target*60-d.reading.seconds)/60)} min lectura</span></div><b>{pct(d)}%</b></article>):<p className="empty">Todavía no hay días guardados. Completa tu primera sesión.</p>}</div></>}
      {tab==="repertoire"&&<><section className="page-title"><span className="eyebrow">REPERTORIO</span><h1>Canciones</h1></section>{data.repertoire.map(song=><Card key={song.id} title={song.title} eyebrow={`${song.mastery}% DOMINIO`}><Progress value={song.mastery}/><a className="primary link" href={song.url} target="_blank" rel="noreferrer">▶ Abrir video</a><Field label="Porcentaje de dominio" type="range" min="0" max="100" value={song.mastery} onChange={e=>setData(x=>({...x,repertoire:x.repertoire.map(s=>s.id===song.id?{...s,mastery:+e.target.value}:s)}))}/><label className="field"><span>Nota para la próxima sesión</span><textarea value={song.notes} onChange={e=>setData(x=>({...x,repertoire:x.repertoire.map(s=>s.id===song.id?{...s,notes:e.target.value}:s)}))}/></label></Card>)}</>}
      {tab==="settings"&&<><section className="page-title"><span className="eyebrow">AJUSTES</span><h1>Tu plan, a tu medida</h1></section><Card title="Metas diarias"><div className="grid2"><Field label="Calorías" type="number" value={data.settings.calories} onChange={e=>setSetting({calories:+e.target.value})}/><Field label="Proteína (g)" type="number" value={data.settings.protein} onChange={e=>setSetting({protein:+e.target.value})}/><Field label="Grasas (g)" type="number" value={data.settings.fat} onChange={e=>setSetting({fat:+e.target.value})}/><Field label="Carbos (g)" type="number" value={data.settings.carbs} onChange={e=>setSetting({carbs:+e.target.value})}/><Field label="Lectura (min)" type="number" value={data.settings.readingMinutes} onChange={e=>setSetting({readingMinutes:+e.target.value})}/></div></Card><Card title="Respaldo y datos"><button className="secondary" onClick={exportJson}>Exportar respaldo JSON</button><label className="secondary file-button">Importar respaldo<input type="file" accept="application/json" onChange={importJson}/></label><button className="danger" onClick={()=>confirm("¿Reiniciar los datos de hoy?")&&updateDay(()=>makeDay(data.settings))}>Reiniciar el día</button></Card><Card title="Instalar en iPhone"><p>En Safari toca <strong>Compartir → Agregar a pantalla de inicio</strong>. Después funcionará también sin conexión.</p></Card></>}
    </main>
    <nav className="bottom" aria-label="Navegación principal">{[["today","⌂","Hoy"],["focus","◉","Enfoque"],["fretboard","♯","Notas"],["history","▦","Historial"],["repertoire","♫","Canciones"],["settings","⚙","Ajustes"]].map(([id,icon,label])=><button key={id} className={tab===id?"active":""} onClick={()=>{setTab(id);setFocus(id==="focus")}}><span>{icon}</span>{label}</button>)}</nav>
  </div>
}

function Routine({day,totals,settings,updateDay,updateExercise,timer,setTimer,setData}:{day:Day;totals:{calories:number;protein:number;fat:number;carbs:number};settings:Settings;updateDay:(fn:(d:Day)=>Day)=>void;updateExercise:(id:string,p:Partial<Exercise>)=>void;timer:boolean;setTimer:(v:boolean)=>void;setData:React.Dispatch<React.SetStateAction<AppData>>}){
 const [meal,setMeal]=useState({name:"",calories:0,protein:0,fat:0,carbs:0}); const [word,setWord]=useState({word:"",meaning:"",example:""});
 const addMeal=()=>{if(!meal.name)return;updateDay(d=>({...d,meals:[...d.meals,{...meal,id:crypto.randomUUID()}]}));setMeal({name:"",calories:0,protein:0,fat:0,carbs:0})};
 const rate=(v:number|null,on:(n:Rating)=>void,label:string)=><RatingScale value={v} onChange={on} label={label}/>;
 return <div className="routine">
  <div className="section-label"><span>PLAN DE HOY</span><b>{day.priority}</b></div>
  <Card title="Cuerpo y nutrición" eyebrow="BLOQUE 1" done={day.nutritionClosed&&day.squatCompleted}><div className="macro-grid">{(["calories","protein","fat","carbs"] as const).map(k=><div key={k}><span>{{calories:"Calorías",protein:"Proteína",fat:"Grasas",carbs:"Carbos"}[k]}</span><strong>{totals[k]} <small>/ {settings[k]}{k!=="calories"&&" g"}</small></strong><div className="mini-bar"><i style={{width:`${Math.min(100,totals[k]/settings[k]*100)}%`}}/></div></div>)}</div><details><summary>+ Registrar comida</summary><div className="grid2"><Field label="Comida" value={meal.name} onChange={e=>setMeal({...meal,name:e.target.value})}/>{(["calories","protein","fat","carbs"] as const).map(k=><Field key={k} label={k} type="number" value={meal[k]} onChange={e=>setMeal({...meal,[k]:+e.target.value})}/>)}</div><button className="secondary" onClick={addMeal}>Agregar comida</button></details>{day.meals.map(m=><div className="meal" key={m.id}><span>{m.name}</span><b>{m.calories} kcal</b></div>)}<button className="secondary" onClick={()=>updateDay(d=>({...d,nutritionClosed:!d.nutritionClosed}))}>{day.nutritionClosed?"✓ Registro cerrado":"Cerrar registro de nutrición"}</button><hr/><h3>Video de sentadillas de frente</h3><div className="grid2"><Field label="Repeticiones" type="number" value={day.squatReps} onChange={e=>updateDay(d=>({...d,squatReps:+e.target.value}))}/><div><span className="input-label">Sensación técnica</span>{rate(day.squatTechnique,n=>updateDay(d=>({...d,squatTechnique:n})),"Técnica de sentadilla")}</div></div><label className="file-drop">Seleccionar video<input type="file" accept="video/*" onChange={e=>updateDay(d=>({...d,videoName:e.target.files?.[0]?.name||""}))}/><small>{day.videoName||"El video se queda en este dispositivo"}</small></label><button className="secondary" onClick={()=>updateDay(d=>({...d,squatCompleted:!d.squatCompleted}))}>{day.squatCompleted?"✓ Sentadillas completadas":"Completar sentadillas"}</button></Card>
  <Card title="Lectura y atención" eyebrow="BLOQUE 2" done={day.reading.completed}><div className="timer">{String(Math.floor(day.reading.seconds/60)).padStart(2,"0")}:{String(day.reading.seconds%60).padStart(2,"0")}</div><div className="button-row"><button className="primary" onClick={()=>setTimer(!timer)}>{timer?"Pausar":"Iniciar / continuar"}</button><button className="secondary" onClick={()=>updateDay(d=>({...d,reading:{...d.reading,seconds:d.reading.seconds+60,target:d.reading.target+1}}))}>+ 1 minuto</button></div><p>Atención</p>{rate(day.reading.attention,n=>updateDay(d=>({...d,reading:{...d.reading,attention:n}})),"Atención en lectura")}<p>Comprensión</p>{rate(day.reading.comprehension,n=>updateDay(d=>({...d,reading:{...d.reading,comprehension:n}})),"Comprensión de lectura")}<label className="field"><span>¿Qué entendiste?</span><textarea value={day.reading.summary} onChange={e=>updateDay(d=>({...d,reading:{...d.reading,summary:e.target.value}}))}/></label><details><summary>+ Agregar palabra desconocida</summary><Field label="Palabra" value={word.word} onChange={e=>setWord({...word,word:e.target.value})}/><Field label="Significado" value={word.meaning} onChange={e=>setWord({...word,meaning:e.target.value})}/><Field label="Ejemplo opcional" value={word.example} onChange={e=>setWord({...word,example:e.target.value})}/><button className="secondary" onClick={()=>{if(word.word&&word.meaning){setData(x=>({...x,vocabulary:[...x.vocabulary,{...word,id:crypto.randomUUID(),date:today()}]}));setWord({word:"",meaning:"",example:""})}}}>Guardar palabra</button></details><button className="secondary" onClick={()=>updateDay(d=>({...d,reading:{...d.reading,completed:!!(d.reading.attention&&d.reading.comprehension)}}))}>Terminar lectura</button></Card>
  <div className="section-label"><span>GUITARRA</span><b>{day.exercises.filter(exerciseDone).length}/{day.exercises.length}</b></div>
  {day.exercises.map((e,i)=><Card key={e.id} title={e.title} eyebrow={`EJERCICIO ${i+1}`} done={exerciseDone(e)} onDone={()=>updateExercise(e.id,{completed:!exerciseDone(e)})}>{e.id==="cg"?<><div className="counter"><strong>{e.count||0}</strong><span>de 20 repeticiones</span></div><div className="button-row"><button className="secondary" onClick={()=>updateExercise(e.id,{count:0,completed:false})}>Reiniciar</button><button className="secondary" onClick={()=>updateExercise(e.id,{count:(e.count||0)+1,completed:(e.count||0)+1>=20})}>+1</button><button className="primary" onClick={()=>updateExercise(e.id,{count:(e.count||0)+5,completed:(e.count||0)+5>=20})}>+5</button></div></>:<>{e.checks&&<div className="checklist">{Object.entries(e.checks).map(([c,v])=><label key={c}><input type="checkbox" checked={v} onChange={()=>{const checks={...e.checks,[c]:!v};updateExercise(e.id,{checks,completed:Object.values(checks).every(Boolean)})}}/><span>{c}</span></label>)}</div>}<div className="grid2">{e.bpm!==undefined&&<Field label="BPM" type="number" value={e.bpm} onChange={x=>updateExercise(e.id,{bpm:+x.target.value})}/>} {e.speed!==undefined&&<Field label="Velocidad" type="number" step="0.05" value={e.speed} onChange={x=>updateExercise(e.id,{speed:+x.target.value})}/>} {e.count!==undefined&&<Field label="Repeticiones / intentos" type="number" min="0" value={e.count} onChange={x=>{const count=x.target.value===""?0:+x.target.value;updateExercise(e.id,{count,...(e.id==="barre"?{completed:count>0}:{})})}}/>}</div>{e.rating!==undefined&&<><p>Precisión / limpieza</p>{rate(e.rating,n=>updateExercise(e.id,{rating:n}),`Precisión de ${e.title}`)}</>}<label className="field"><span>Nota breve</span><input value={e.notes||""} onChange={x=>updateExercise(e.id,{notes:x.target.value})}/></label></>}</Card>)}
  <Card title="Repertorio · Wonderwall" eyebrow="BLOQUE FINAL" done={!!day.songs.wonderwall}><a className="primary link" href="https://www.youtube.com/watch?v=LRXRm0eMZZY" target="_blank" rel="noreferrer">▶ Abrir video</a><div className="checklist">{["Acordes dominados","Patrón rítmico dominado","Tocar por secciones","Tocar completa"].map(c=><label key={c}><input type="checkbox" checked={day.songs.wonderwall?.checks?.[c]||false} onChange={x=>updateDay(d=>({...d,songs:{...d.songs,wonderwall:{difficulty:d.songs.wonderwall?.difficulty||null,notes:d.songs.wonderwall?.notes||"",checks:{...d.songs.wonderwall?.checks,[c]:x.target.checked}}}}))}/><span>{c}</span></label>)}</div><p>Dificultad de hoy</p>{rate(day.songs.wonderwall?.difficulty,n=>updateDay(d=>({...d,songs:{...d.songs,wonderwall:{checks:d.songs.wonderwall?.checks||{},notes:d.songs.wonderwall?.notes||"",difficulty:n}}})),"Dificultad Wonderwall")}</Card>
  <Card title="Cierre del día" eyebrow="REFLEXIÓN" done={day.saved}><p>Atención general</p>{rate(day.attention,n=>updateDay(d=>({...d,attention:n})),"Atención general")}<p>Energía final</p>{rate(day.finalEnergy,n=>updateDay(d=>({...d,finalEnergy:n})),"Energía final")}<p>Satisfacción</p>{rate(day.satisfaction,n=>updateDay(d=>({...d,satisfaction:n})),"Satisfacción")}<label className="field"><span>¿Qué salió mejor hoy?</span><textarea value={day.bestResult} onChange={e=>updateDay(d=>({...d,bestResult:e.target.value}))}/></label><label className="field"><span>¿Qué necesitas corregir mañana?</span><textarea value={day.correction} onChange={e=>updateDay(d=>({...d,correction:e.target.value}))}/></label><label className="field"><span>Prioridad para mañana</span><select value={day.nextPriority} onChange={e=>updateDay(d=>({...d,nextPriority:e.target.value}))}><option value="">Elegir</option>{priorities.map(p=><option key={p}>{p}</option>)}</select></label><div className="summary-box">Completaste {completedCount(day)} de {taskCount(day)} tareas. Avanzaste especialmente en {day.priority||"tu práctica"}. Lo pendiente puede retomarse mañana.</div><button className="primary" onClick={()=>updateDay(d=>({...d,saved:true}))}>Guardar y cerrar el día</button></Card>
 </div>
}
